### PR TITLE
Allow plugin to be installed with chai 2

### PR DESCRIPTION
**Pull request by Koblaid**
PR for #8 

This seems to work. The tests pass and I used it in my code. Haven't done any further testing.

### CODE REVIEW

**Comment by michelsalib** [comment]
Thanks mate :)

**Comment by Steditor** [comment]
Thank you!
@michelsalib It would be great if you could publish this version on npm!

**Comment by michelsalib** [comment]
Done !

**Comment by Steditor** [comment]
:+1:

**Comment by Koblaid** [comment]
:+1:

**Pull request merged**
